# Project types
PROJECT_TYPE_ACADEMIC = "academic"
PROJECT_TYPE_PERSONAL = "personal"
PROJECT_TYPE_ENTERPRISE = "enterprise"
PROJECT_TYPE_OPENSOURCE = "opensource"
PROJECT_TYPE_FREELANCE = "freelance"

PROJECT_TYPE_CHOICES = [
    PROJECT_TYPE_ACADEMIC,
    PROJECT_TYPE_PERSONAL,
    PROJECT_TYPE_ENTERPRISE,
    PROJECT_TYPE_OPENSOURCE,
    PROJECT_TYPE_FREELANCE,
]

# Deploy log badge types
BADGE_TYPE_OK = "ok"
BADGE_TYPE_WARN = "warn"
BADGE_TYPE_ERR = "err"
BADGE_TYPE_INFO = "info"

BADGE_TYPE_CHOICES = [BADGE_TYPE_OK, BADGE_TYPE_WARN, BADGE_TYPE_ERR, BADGE_TYPE_INFO]

# Contact message status
MESSAGE_STATUS_UNREAD = "unread"
MESSAGE_STATUS_READ = "read"

# Skill categories
SKILL_CATEGORY_FRONTEND = "frontend"
SKILL_CATEGORY_BACKEND = "backend"
SKILL_CATEGORY_DATABASE = "database"
SKILL_CATEGORY_DEVOPS = "devops"
SKILL_CATEGORY_OTHER = "other"

SKILL_CATEGORY_CHOICES = [
    SKILL_CATEGORY_FRONTEND,
    SKILL_CATEGORY_BACKEND,
    SKILL_CATEGORY_DATABASE,
    SKILL_CATEGORY_DEVOPS,
    SKILL_CATEGORY_OTHER,
]